# Generated by Django 3.2 on 2021-04-08 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_poduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poduct',
            new_name='Product',
        ),
    ]
